"use client";

import { useEffect, useMemo, useState } from "react";
import MainLayout from "../components/layout/MainLayout";
import { supabase } from "@/lib/supabase";

const money=(v:any)=>Number(v||0).toLocaleString("vi-VN")+" đ";
const now=new Date();

export default function ReportsPage(){
 const [year,setYear]=useState(now.getFullYear()); const [month,setMonth]=useState<number|"all">("all");
 const [jobs,setJobs]=useState<any[]>([]),[days,setDays]=useState<any[]>([]),[payments,setPayments]=useState<any[]>([]),[assignments,setAssignments]=useState<any[]>([]),[salaryPayments,setSalaryPayments]=useState<any[]>([]),[advances,setAdvances]=useState<any[]>([]),[tx,setTx]=useState<any[]>([]);
 useEffect(()=>{(async()=>{const r=await Promise.all([supabase.from("jobs").select("*"),supabase.from("job_days").select("*").order("shooting_date"),supabase.from("customer_payments").select("*"),supabase.from("job_assignments").select("*"),supabase.from("salary_payments").select("*"),supabase.from("salary_advances").select("*"),supabase.from("finance_transactions").select("*")]);setJobs(r[0].data||[]);setDays(r[1].data||[]);setPayments(r[2].data||[]);setAssignments(r[3].data||[]);setSalaryPayments(r[4].data||[]);setAdvances(r[5].data||[]);setTx(r[6].data||[])})()},[]);
 const prefix=month==="all"?`${year}-`:`${year}-${String(month).padStart(2,"0")}`;
 const inPeriod=(v:any)=>String(v||"").startsWith(prefix);
 const periodJobIds=useMemo(()=>new Set(days.filter(d=>inPeriod(d.shooting_date)).map(d=>d.job_id)),[days,prefix]);
 const periodJobs=jobs.filter(j=>periodJobIds.has(j.id));
 const revenue=periodJobs.reduce((s,j)=>s+Number(j.total_price||0),0);
 const customerCollected=payments.filter(p=>inPeriod(p.payment_date)).reduce((s,p)=>s+Number(p.amount||0),0);
 const otherIncome=tx.filter(t=>t.transaction_type==="income"&&t.source_type!=="customer_payment"&&inPeriod(t.transaction_date)).reduce((s,t)=>s+Number(t.amount||0),0);
 const operatingExpense=tx.filter(t=>t.transaction_type==="expense"&&!String(t.source_type||"").startsWith("salary_")&&inPeriod(t.transaction_date)).reduce((s,t)=>s+Number(t.amount||0),0);
 const salaryPaid=salaryPayments.filter(p=>inPeriod(p.payment_date)).reduce((s,p)=>s+Number(p.amount||0),0)+advances.filter(p=>inPeriod(p.advance_date)).reduce((s,p)=>s+Number(p.amount||0),0);
 const customerDebt=periodJobs.reduce((s,j)=>s+Math.max(Number(j.debt||0),0),0);
 const salaryGenerated=assignments.filter(a=>periodJobIds.has(a.job_id)).reduce((s,a)=>s+Number(a.salary_amount||0),0);
 const salaryDue=Math.max(salaryGenerated-salaryPaid,0);
 const totalCashIn=customerCollected+otherIncome,totalCashOut=operatingExpense+salaryPaid,netCash=totalCashIn-totalCashOut,estimatedProfit=revenue+otherIncome-operatingExpense-salaryGenerated;
 const monthly=Array.from({length:12},(_,i)=>{const p=`${year}-${String(i+1).padStart(2,"0")}`;const ids=new Set(days.filter(d=>String(d.shooting_date||"").startsWith(p)).map(d=>d.job_id));const js=jobs.filter(j=>ids.has(j.id));return {m:i+1,revenue:js.reduce((s,j)=>s+Number(j.total_price||0),0),collected:payments.filter(x=>String(x.payment_date||"").startsWith(p)).reduce((s,x)=>s+Number(x.amount||0),0),debt:js.reduce((s,j)=>s+Math.max(Number(j.debt||0),0),0),expense:tx.filter(x=>x.transaction_type==="expense"&&!String(x.source_type||"").startsWith("salary_")&&String(x.transaction_date||"").startsWith(p)).reduce((s,x)=>s+Number(x.amount||0),0)};});
 return <MainLayout><div className="mx-auto max-w-7xl"><div className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-2xl font-bold sm:text-3xl">Thống kê tài chính</h1><p className="text-slate-500">Xem theo tháng hoặc cả năm.</p></div><div className="flex gap-2"><select value={month} onChange={e=>setMonth(e.target.value==="all"?"all":Number(e.target.value))} className="rounded-xl border bg-white p-3"><option value="all">Cả năm</option>{Array.from({length:12},(_,i)=><option key={i} value={i+1}>Tháng {i+1}</option>)}</select><select value={year} onChange={e=>setYear(Number(e.target.value))} className="rounded-xl border bg-white p-3">{[year-2,year-1,year,year+1].map(y=><option key={y}>{y}</option>)}</select></div></div>
 <div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Card t="Tổng giá trị job" v={money(revenue)}/><Card t="Đã thu khách" v={money(customerCollected)} tone="green"/><Card t="Khách còn nợ" v={money(customerDebt)} tone="red" note="Tiền khách chưa thanh toán cho BEEN MEDIA"/><Card t="Cần trả thợ" v={money(salaryDue)} tone="orange"/><Card t="Thu khác" v={money(otherIncome)} tone="green"/><Card t="Chi phí hoạt động" v={money(operatingExpense)} tone="red" note="Thiết bị, xăng xe, quảng cáo, ăn uống... không gồm lương thợ"/><Card t="Đã trả/ứng thợ" v={money(salaryPaid)} tone="orange"/><Card t="Lợi nhuận dự kiến" v={money(estimatedProfit)} tone={estimatedProfit>=0?"blue":"red"}/></div>
 <div className="mt-5 rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-sm font-semibold text-slate-700">Dòng tiền thực trong kỳ</p><div className="mt-3 grid grid-cols-1 gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-emerald-50 p-4"><p className="text-xs font-medium text-emerald-800">Tiền vào</p><p className="mt-1 text-lg font-bold text-emerald-700">{money(totalCashIn)}</p></div><div className="rounded-2xl bg-orange-50 p-4"><p className="text-xs font-medium text-orange-800">Tiền ra</p><p className="mt-1 text-lg font-bold text-orange-700">{money(totalCashOut)}</p></div><div className="rounded-2xl bg-blue-50 p-4"><p className="text-xs font-medium text-blue-800">Còn lại</p><p className={`mt-1 text-lg font-bold ${netCash>=0?"text-blue-700":"text-red-700"}`}>{money(netCash)}</p></div></div></div>
 {month==="all"&&<div className="mt-5 overflow-x-auto rounded-3xl bg-white p-4 shadow"><table className="w-full min-w-[760px]"><thead><tr className="border-b bg-slate-50"><th className="p-3 text-left">Tháng</th><th className="p-3 text-right">Doanh thu</th><th className="p-3 text-right">Đã thu</th><th className="p-3 text-right">Còn nợ</th><th className="p-3 text-right">Chi phí hoạt động</th></tr></thead><tbody>{monthly.map(r=><tr key={r.m} className="border-b"><td className="p-3 font-bold">Tháng {r.m}</td><td className="p-3 text-right">{money(r.revenue)}</td><td className="p-3 text-right text-emerald-700">{money(r.collected)}</td><td className="p-3 text-right text-red-600">{money(r.debt)}</td><td className="p-3 text-right">{money(r.expense)}</td></tr>)}</tbody></table></div>}
 </div></MainLayout>;
}
function Card({t,v,tone="",note=""}:{t:string,v:string,tone?:string,note?:string}){const c=tone==="green"?"text-emerald-700":tone==="red"?"text-red-600":tone==="orange"?"text-orange-600":tone==="blue"?"text-blue-700":"text-slate-900";return <div className="rounded-3xl bg-white p-4 shadow-sm ring-1 ring-slate-100"><p className="text-xs text-slate-500">{t}</p><p className={`mt-2 text-lg font-bold ${c}`}>{v}</p>{note&&<p className="mt-1 text-[11px] leading-4 text-slate-400">{note}</p>}</div>}
